import { pool } from "./database.js";
import { fetchFlowersFromAPI } from "../services/plantAPI.js";



const flowerMeanings ={
  "Abatina": "Fickleness",
  "Acanthus": "The fine art, Artifice",
  "Aloe":  "Grief, Woe",
  "Amaryllis": "Pride, pastorial poetry",
  "Anemone": "Forsaken",
  "Angelica": "Inspiration",
  "Apple Blossom": "Preference",
  "Arborvitae": "Unchanging friendship",
  "Aster": "symbol of love, daintiness",
  "Azalea": "Temperance, fragile passion, chinese symbol of womanhood",
  "Baby's Breath": "Everlasting love",
  "Bachelor's Button": "Single blessedness",
  "Basil": "Good wishes, best wishes",
  "Bay tree": "Glory",
  "Begonia": "Beware",
  "Belledonna":"Silence",
  "Bells-of-Ireland": "Good luck",
  "Bittersweet": "Truth",
  "Black-eyed Susan": "Justice",
  "Bluebell": "Humility",
  "Borage" : "Bluntness",
  "Butterfly weed": "Let me go",
  "Cactus": "Endurance",
  "Calla lily": "Magnificent beauty",
  "Pink Camellia": "Longing",
  "Red Camellia": "Passion",
  "White Camellia": "Adoration",
  "Candytuft": "Indifference",
  "Carnation":"Fascination, women love",
  "Pink Carnation": "I'll never forget you",
  "Red Carnation": "Admiration, Deep love",
  "purple Carnation": "Capriciousness",
  "yellow Carnation": "Disappointment, rejection",
  "White Carnation": "Pure love, good luck",
  "Cattail": "Peace, prosperity",
  "Chamomile": "Patience, rest",
  "Chives": "Usefulness",
  "Red Chrysanthemum": "I love you",
  "White Chrysanthemum": "Loyal love",
  "Yellow Chrysanthemum": "Slighted love",
  "Clemantis": "Mental beauty",
  "Cleome": "Elope with me",
  "Clover": "Good luck",
  "Columbine": "Foolishness, Folly",
  "Coreopsis": "Always cheerful",
  "Crocus": "Cheerfulness",
  "Cyclamen": "Resignation and goodbye",
  "Daffodil": "Unrequited love, regard",
  "Daisy": "Innocence, loyal love, purity",
  "Dandelion": "Happiness,faithfulness",
  "Daylily": "Coquetry, Chinese symbol of motherhood",
  "Edelweiss": "Devotion",
  "Evening Primrose": "Inconstancy",
  "Fennel": "Flattery",
  "Fern": "Fasination, secret bond of love",
  "Fir": "Time",
  "Flax": "Domestic symbol",
  "Forget-Me-Not": "True love, remembrance",
  "Forsythia": "Anticipation",
  "Gardenia": "Secret love",
  "Garlic": "Strength, courage",
  "Geranium": "Foolishness",
  "Gladiolus": "Sincerity, victory",
  "Gloxinia": "Love at first sight",
  "Goldenrod": "Encouragement",
  "Heliotrope": "Devotion, eternal love",
  "Hibiscus": "Delicate beauty",
  "Holly": "Defense, domestic happiness",
  "Honeysuckle": "Generosity",
  "Hyacinth": "Playfulness, rashness",
  "Blue Hyacinth": "Constancy",
  "Purple Hyacinth": "Sorrow",
  "Yellow Hyacinth": "Jealousy",
  "White Hyacinth": "Loveliness, prayers for someone",
  "Hydrangea": "Frigidity and heartlessness",
  "Hyssop": "Sacrifice, purification",
  "Iris": "Faith, hope, wisdom",
  "Ivy": "Fidelity",
  "Jasmine": "Grace, elegance",
  "Lady's Slipper": "Capricious beauty",
  "Larkspur": "Levity, fickleness",
  "Lilac": "Old love, joy of youth",
  "Lily": "Purity, refined beauty",
  "Lily of the Valley": "Return of happiness, Sweetness, humility",
  "Lavender": "Distrust",
  "lotus": "Enlightenment, rebirth",
  "Magnolia": "Dignity, nobility",
  "Marigold": "Despair and grief over a loved one",
  "marjoram": "Happiness",
  "Mint": "Virtue",
  "Mistletoe": "Affection",
  "Mock orange": "Deceit",
  "Morning Glory": "Affection",
  "Monkshood": "Caution",
  "Moss": "Maternal love",
  "Mugwort": "Happiness in love",
  "Myrtle": "Love in marriage",
  "Narcissus": "Egotism",
  "Nasturtium": "Patriotism, victory in battle",
  "oak": "Strength and endurance",
  "Orchid": "Refinement, beauty, love",
  "Pansy": "Thoughts",
  "Peony": "Shame, bashfulness",
  "Periwinkle": "Friendship",
  "Petunia": "Resentment and anger",
  "Pine":"Hope, humility, piety",
  "Poppy": "Consolation, remembrance, eternal sleep",
  "Primrose": "Young love",
  "Rhododendron": "Danger",
  "Rosebud": "Beauty, innocent love",
  "Pink Rose": "Admiration, gratitude",
  "Red Rose": "Love, passion",
  "yellow Rose": "Decrease of love, jealousy, infidelity",
  "White Rose": "Purity, innocence",
  "Rosemary": "Remembrance",
  "Sage": "Wisdom, immortality",
  "Saffron": "Joy and happiness",
  "Salvia": "Forever mine",
  "Smilax": "Loveliness",
  "Snapdragon": "Graciousness, deception",
  "sorrel": "Affection",
  "Sweet Pea": "Goodbye",
  "Sweet William": "Gallantry",
  "Tarragon": "Fascination",
  "Tiger Lily": "Wealth and pride",
  "Thistle": "Nobility of character",
  "Thyme": "Courage, bravery",
  "Tulip": "Perfect love",
  "red Tulip": "Declaration of love",
  "yellow Tulip": "Cheerful thoughts",
  "White Tulip": "Forgiveness",
  "Violet": "Modesty, faithfulness, watchfulness",
  "Willow": "Sadness",
  "Wisteria": "Welcome, blissful, devotion",
  "Yarrow": "Everlasting love",
  "Zinnia": "Thoughts of absent friends",
}

export const seedFlowers = async () => {
  const flowers = await fetchFlowersFromAPI();
  for (const flower of flowers) {
    // const nameKey = flower.name?.toLowerCase().trim();
    // const meaning = flowerMeanings[nameKey] ?? flower.flower_meaning;
    const nameKey = flower.name?.toLowerCase().trim();
    // Try exact match first, then partial match
    const meaning =
      flowerMeanings[nameKey] ??
      Object.entries(flowerMeanings).find(([k]) => nameKey?.includes(k))?.[1] ??
      flower.flower_meaning;
      
    await pool.query(
      `INSERT INTO flowers (name, description, flower_family, flower_meaning, image_url)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT DO NOTHING`,
      [
        flower.name,
        flower.description,
        flower.flower_family,
        meaning, // <-- use the enriched meaning here
        flower.image_url,
      ],
    );
  }

  console.log(`Seeded ${flowers.length} flowers`);
};
